data_dir: /home/padl21t1/data_folder/words/
hwr_default_model: /home/padl21t1/HWR_using_GAN/pretrained_models/hwr/seq2seq-45.model
gan_default_model: /home/padl21t1/HWR_using_GAN/pretrained_models/gan/contran-2050.model
number_training_epochs: 1
iam_writer_mappings: data/img_writer_mapping.txt
result_paths:
  synthesized_images: synthesized_images/
  sample_partitions: train_images_names/
  labels_path: label_files/
  models:
text_corpus: GAN/corpora_english/brown-azAZ.tr
