data_dir: /home/padl21t1/data_folder/words/
hwr_default_model: /home/padl21t1/HWR_using_GAN/pretrained_models/hwr/seq2seq-45.model
gan_default_model: /home/padl21t1/HWR_using_GAN/pretrained_models/gan/contran-2050.model
